### PR TITLE
Added support for creating a user ready to import password via inline…

### PR DESCRIPTION
**Pull request by dogeared**
… password hook

## Description
Expands on the `UserBuilder` to include creating a user in state that is ready to have their password imported via inline password hook.

## Category

- [ ] Bugfix
- [x] Enhancement
- [ ] New Feature
- [ ] Configuration Change
- [ ] Versioning Change
- [x] Unit Test(s)
- [ ] Documentation

### CODE REVIEW

**Comment by bdemers** [comment]
@arvindkrishnakumar-okta can you push this to a branch within this repo (so the ITs run)

**Comment by arvindkrishnakumar-okta** [comment]
> @arvindkrishnakumar-okta can you push this to a branch within this repo (so the ITs run)

will do.

**Comment by arvindkrishnakumar-okta** [comment]
> > @arvindkrishnakumar-okta can you push this to a branch within this repo (so the ITs run)
> 
> will do.

@bdemers - https://github.com/okta/okta-sdk-java/pull/455

**Comment by arvindkrishnakumar-okta** [comment]
> > > @arvindkrishnakumar-okta can you push this to a branch within this repo (so the ITs run)
> > 
> > 
> > will do.
> 
> @bdemers - #455

All tests pass - this PR is good to merge.

**Pull request merged**
