### PR TITLE
Fix enumUnknownDefaultCase in OpenAPI generator

### PR DESCRIPTION
**Pull request by clementdenis**
## Description
The recently added enumUnknownDefaultCase was not actually used. It now is:

```java
public enum ChangeEnum {

    CHANGE("CHANGE"),
    
    KEEP_EXISTING("KEEP_EXISTING"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

   ...

}
```

## Category
- [x] Bugfix
- [ ] Enhancement
- [ ] New Feature
- [ ] Library Upgrade
- [ ] Configuration Change
- [ ] Versioning Change
- [ ] Unit or Integration Test(s) 
- [ ] Documentation

## Signoff
- [x] I have submitted a CLA for this PR
- [x] Each commit message explains what the commit does
- [x] I have updated documentation to explain what my PR does
- [x] My code is covered by tests if required
- [x] I did not edit any automatically generated files

### CODE REVIEW

**Comment by arvindkrishnakumar-okta** [comment]
@clementdenis Thanks much for fixing this!

I'll close this in favor of mergeable PR https://github.com/okta/okta-sdk-java/pull/1002.

**Comment by literallyjustroy** [comment]
I wonder if this change led to the mis-casing of this method: `addemailAddressesItem`

**Comment by arvindkrishnakumar-okta** [comment]
@literallyjustroy Can you please elaborate?

**Comment by literallyjustroy** [comment]
Yes, sorry for the quick comment - I was in the middle of upgrading from 16.0.0 -> 17.00 and was looking around for a possible cause.

The 'addEmailAddressItem' method in the [BouncesRemoveListObj](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/model/BouncesRemoveListObj.html) class was renamed to 'addemailAddressItem'. That change in casing felt odd and perhaps unintentional. Could also have been related to the api generator upgrade as well.

Sorry I'm not super familiar with the project layout so wasn't able pinpoint the source of the change.

**Comment by arvindkrishnakumar-okta** [comment]
@literallyjustroy Thanks for the clarification!

Yes, it appears to be caused by the Open API Generator upgrade and was unintentional.

**Pull request closed without merging**
