### PR TITLE
Add support for importing SHA1 hashed passwords

### PR DESCRIPTION
**Pull request by davidmortiz**

### CODE REVIEW

**Comment by davidmortiz** [comment]
@bdemers Some of us work on old things 😄.  This PR is a quick change to expose importing SHA-1 hashed passwords which is already supported by the OKTA API

**Comment by bdemers** [comment]
@davidmortiz 
Looks great!  Thanks for the PR! (bonus points for adding the test)

**Comment by bdemers** [comment]
@davidmortiz Can I get you to sign a CLA: https://developer.okta.com/cla/
After we have it on file, I'll get this merged and into the next release!

**Comment by davidmortiz** [comment]
@bdemers FYI my company's legal department should be sending you over the agreement today.  Sorry, it took a little bit.

**Comment by davidmortiz** [comment]
@bdemers Any updates?  Anything I can do to make the legal stuff go faster?

**Comment by bdemers** [comment]
Hey @davidmortiz!

We haven't received a CLA yet.  Can you confirm it was sent?

Thanks again!

**Comment by davidmortiz** [comment]
There was some confusion on our end, the agreement was sent over to the email address on the link you gave me.  Sorry for making this so confusing.

**Comment by bdemers** [comment]
Thanks @davidmortiz !

**Pull request merged**
