### PR TITLE
Removed incorrect heading !

### PR DESCRIPTION
**Pull request by JanardhanSharma**
The rate limiting is limiting the number of api calls to a threshold. There is no provision provided to limit the rate. Connection retry makes more sense it does a corrective measure and not the preventive measure of rate limiting.

## Category
- [ ] Bugfix
- [ ] Enhancement
- [ ] New Feature
- [ ] Library Upgrade
- [ ] Configuration Change
- [ ] Versioning Change
- [ ] Unit or Integration Test(s) 
- [x] Documentation

## Signoff
- [ ] I have submitted a CLA for this PR
- [ ] Each commit message explains what the commit does
- [ ] I have updated documentation to explain what my PR does
- [ ] My code is covered by tests if required
- [ ] I did not edit any automatically generated files

### CODE REVIEW

**Review by arvindkrishnakumar-okta — APPROVED** [review]

**Comment by JayNewstrom** [comment]
I thought retries should occur due to a 429 https://developer.okta.com/docs/reference/rate-limits/

Is this not happening @arvindkrishnakumar-okta?

**Comment by arvindkrishnakumar-okta** [comment]
> I thought retries should occur due to a 429 https://developer.okta.com/docs/reference/rate-limits/
> 
> Is this not happening @arvindkrishnakumar-okta?

@jaynewstrom-okta it would happen (see https://github.com/okta/okta-commons-java/blob/master/http/http-api/src/main/java/com/okta/commons/http/RetryRequestExecutor.java#L165-L173).

**Comment by arvindkrishnakumar-okta** [comment]
@JanardhanSharma it'd be worth adding a note that retry would happen for 429 error which is a result of rate limiting.

**Review by arvindkrishnakumar-okta — CHANGES_REQUESTED** [review]
left a comment

**Review by arvindkrishnakumar-okta — APPROVED** [review]

**Pull request merged**
