### PR TITLE
IDEA: Lookup config file based on XdgConfig

### PR DESCRIPTION
**Pull request by bdemers**
see: okta/okta-commons-java#38

NOTE: tests will fail as above PR is not merged

### CODE REVIEW

**Review by sergiishamrai-okta — COMMENTED** [review]
line 56:
import java.io.File;

Could be removed

**Comment by bdemers** [comment]
Thanks @senthilkumaran-okta the linting (PMD in this case will catch that).

I'm mostly interested in floating the idea of using the Xdg spec to resolve configuration files.  This is something that needs to be considered across all of our SDKs (not just the Java project)

**Review by sergiishamrai-okta — APPROVED** [review]
Looks good

**Comment by bdemers** [comment]
@sergiishamrai-okta This should be reverted until this is discussed with the other SDK owners.
see #470

**Pull request merged**
